# Generated by Django 2.1.2 on 2018-10-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rulebook', models.CharField(blank=True, max_length=256, null=True)),
                ('image_id', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('label', models.CharField(blank=True, max_length=128, null=True)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
