# Generated by Django 2.1.2 on 2018-10-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageref',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imageref',
            name='image_id',
        ),
        migrations.AddField(
            model_name='imageref',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
