# Generated by Django 2.1.2 on 2018-10-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181019_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageref',
            name='image_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
